name: Deployment Workflow
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    steps:
    - name: Build and deploy
      uses: appleboy/ssh-action@master
      env:
        CONTAINER: pokemon-game-front
        IMAGE: pokemon-game-front
        TAG: latest
        WORKDIR: portfolio/vue_projects/pokemon-game-vue
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        envs: CONTAINER, IMAGE, TAG, WORKDIR
        script: |
          cd $WORKDIR
          git pull
          cp .env.example .env
          source .env
          docker build -t $IMAGE:$TAG .
          docker stop $CONTAINER
          docker rm $CONTAINER
          docker run -d --restart always --name $CONTAINER -p $PORT:80 $IMAGE:$TAG
          docker system prune -f